
--------------- INSERT TEST DATA
INSERT INTO COUNTRY VALUES (COUNTRY_ID_SEQ.NEXTVAL,'BRITAN',23);
INSERT INTO COUNTRY VALUES (COUNTRY_ID_SEQ.NEXTVAL,'USA',12);
INSERT INTO COUNTRY VALUES (COUNTRY_ID_SEQ.NEXTVAL,'CHINA',43);
INSERT INTO COUNTRY VALUES (COUNTRY_ID_SEQ.NEXTVAL,'RUSSIA',21);
INSERT INTO COUNTRY VALUES (COUNTRY_ID_SEQ.NEXTVAL,'BELARUS',45);
INSERT INTO COUNTRY VALUES (COUNTRY_ID_SEQ.NEXTVAL,'MEXICO',2);
INSERT INTO COUNTRY VALUES (COUNTRY_ID_SEQ.NEXTVAL,'EMIRATES',7);
INSERT INTO COUNTRY VALUES (COUNTRY_ID_SEQ.NEXTVAL,'NEW ZELAND',77);
INSERT INTO COUNTRY VALUES (COUNTRY_ID_SEQ.NEXTVAL,'NIGGER',9);
INSERT INTO COUNTRY VALUES (COUNTRY_ID_SEQ.NEXTVAL,'SAR',10);
---------------
INSERT INTO DIRECTORS VALUES (DEFAULT,DEFAULT,'KRISTOFER','NOLAN',1);
INSERT INTO DIRECTORS VALUES (DEFAULT,DEFAULT,'ANNIKEVICH','POPOV',2);
INSERT INTO DIRECTORS VALUES (DEFAULT,DEFAULT,'XUNXI','XUN',3);
INSERT INTO DIRECTORS VALUES (DEFAULT,DEFAULT,'VALILEV','VASILIY',4);
INSERT INTO DIRECTORS VALUES (DEFAULT,DEFAULT,'DERGIENKO','DERJINSKIY',5);
INSERT INTO DIRECTORS VALUES (DEFAULT,DEFAULT,'VALET','VOLAN',6);
INSERT INTO DIRECTORS VALUES (DEFAULT,DEFAULT,'GENDERIOVICH','BILAN',7);
INSERT INTO DIRECTORS VALUES (DEFAULT,DEFAULT,'VINAGIVECH','VLAD',8);
INSERT INTO DIRECTORS VALUES (DEFAULT,DEFAULT,'JOJICH','BANS',9);
INSERT INTO DIRECTORS VALUES (DEFAULT,DEFAULT,'lolich','vanya',10);
---------------
INSERT INTO GENRE VALUES (DEFAULT,DEFAULT,'TRILLER');
INSERT INTO GENRE VALUES (DEFAULT,DEFAULT,'CAMEDY');
INSERT INTO GENRE VALUES (DEFAULT,DEFAULT,'ACTION');
INSERT INTO GENRE VALUES (DEFAULT,DEFAULT,'HORROR');
INSERT INTO GENRE VALUES (DEFAULT,DEFAULT,'HISTORICAL');
INSERT INTO GENRE VALUES (DEFAULT,DEFAULT,'DOCUMENTARY');
---------------
INSERT INTO FILMS VALUES (DEFAULT,1,'BAKI:OGRS SON',1,9,TO_DATE('7/12/2015', 'DD/MM/YYYY'));
INSERT INTO FILMS VALUES (DEFAULT,2,'AVENGERS 1',2,7,TO_DATE('26/12/2014', 'DD/MM/YYYY'));
INSERT INTO FILMS VALUES (DEFAULT,3,'AVENGERS 2',3,2,TO_DATE('17/12/2013', 'DD/MM/YYYY'));
INSERT INTO FILMS VALUES (DEFAULT,4,'AVENGERS 3',4,2,TO_DATE('23/12/2005', 'DD/MM/YYYY'));
INSERT INTO FILMS VALUES (DEFAULT,5,'AVENGERS 4',5,8,TO_DATE('21/12/2019', 'DD/MM/YYYY'));
INSERT INTO FILMS VALUES (DEFAULT,6,'AVENGERS 5',6,5,TO_DATE('11/12/1999', 'DD/MM/YYYY'));
INSERT INTO FILMS VALUES (DEFAULT,7,'AVENGERS 6',6,10,TO_DATE('9/12/2000', 'DD/MM/YYYY'));
INSERT INTO FILMS VALUES (DEFAULT,8,'AVENGERS 7',2,4,TO_DATE('11/12/2002', 'DD/MM/YYYY'));
INSERT INTO FILMS VALUES (DEFAULT,9,'AVENGERS 8',3,3,TO_DATE('13/02/1968', 'DD/MM/YYYY'));
INSERT INTO FILMS VALUES (DEFAULT,10,'DRIVE 8',2,3,TO_DATE('13/02/1968', 'DD/MM/YYYY'));
INSERT INTO FILMS VALUES (DEFAULT,11,'DAS 8',2,3,TO_DATE('13/02/1968', 'DD/MM/YYYY'));
---------------
SELECT COUNT(*) FROM COUNTRY;
INSERT INTO HALL VALUES (1,231,'RED',12,127);
INSERT INTO HALL VALUES (2,121,'GREEN',7,36);
INSERT INTO HALL VALUES (3,131,'BLACK',16,150);
INSERT INTO HALL VALUES (4,31,'BROWN',24,225);
---------------
INSERT INTO SESSIONF VALUES (DEFAULT,2,'TRILLER',231,127,127,20,TO_DATE('11/12/2022', 'DD/MM/YYYY'));
INSERT INTO SESSIONF VALUES (DEFAULT,2,'TRILLER',231,127,127,37,TO_DATE('11/12/2022', 'DD/MM/YYYY'));
INSERT INTO SESSIONF VALUES (DEFAULT,1,'TRILLER',121,36,36,25,TO_DATE('11/12/2022', 'DD/MM/YYYY'));
INSERT INTO SESSIONF VALUES (DEFAULT,3,'TRILLER',231,127,127,21,TO_DATE('11/12/2022', 'DD/MM/YYYY'));
INSERT INTO SESSIONF VALUES (DEFAULT,4,'TRILLER',131,150,150,50,TO_DATE('11/12/2022', 'DD/MM/YYYY'));
INSERT INTO SESSIONF VALUES (DEFAULT,6,'TRILLER',31,225,225,70,TO_DATE('11/12/2022', 'DD/MM/YYYY'));
INSERT INTO SESSIONF VALUES (DEFAULT,7,'TRILLER',31,225,225,34,TO_DATE('11/12/2022', 'DD/MM/YYYY'));
INSERT INTO SESSIONF VALUES (DEFAULT,7,'TRILLER',31,200,225,34,TO_DATE('11/12/2022', 'DD/MM/YYYY'));
